server/src/FullSix/ProjectForecastBundle/Entity/Daysoffs.php
<?php

namespace FullSix\ProjectForecastBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Daysoffs
 *
 * //unsued in the current version
 * //@ORM\Table()
 * //@ORM\Entity(repositoryClass="FullSix\ProjectForecastBundle\Repository\DaysoffsRepository")
 */
class Daysoffs
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Users
     *
     * @ORM\ManyToOne(targetEntity="Users", inversedBy="id")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="DaysoffsUsersId", referencedColumnName="id", nullable=false)
     * })
     */
    protected $daysoffsuserid;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="DaysoffsDate", type="date", nullable=false)
     */
    private $DaysoffsDate;

    /**
     * @var boolean
     *
     * @ORM\Column(name="DaysoffsMorning", type="boolean", nullable=false)
     */
    private $DaysoffsMorning;

    /**
     * @var boolean
     *
     * @ORM\Column(name="DaysoffsAfternoon", type="boolean", nullable=false)
     */
    private $DaysoffsAfternoon;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set DaysoffsDate
     *
     * @param \DateTime $daysoffsDate
     * @return Daysoffs
     */
    public function setDaysoffsDate($daysoffsDate)
    {
        $this->DaysoffsDate = $daysoffsDate;
    
        return $this;
    }

    /**
     * Get DaysoffsDate
     *
     * @return \DateTime 
     */
    public function getDaysoffsDate()
    {
        return $this->DaysoffsDate;
    }

    /**
     * Set DaysoffsMorning
     *
     * @param boolean $daysoffsMorning
     * @return Daysoffs
     */
    public function setDaysoffsMorning($daysoffsMorning)
    {
        $this->DaysoffsMorning = $daysoffsMorning;
    
        return $this;
    }

    /**
     * Get DaysoffsMorning
     *
     * @return boolean 
     */
    public function getDaysoffsMorning()
    {
        return $this->DaysoffsMorning;
    }

    /**
     * Set DaysoffsAfternoon
     *
     * @param boolean $daysoffsAfternoon
     * @return Daysoffs
     */
    public function setDaysoffsAfternoon($daysoffsAfternoon)
    {
        $this->DaysoffsAfternoon = $daysoffsAfternoon;
    
        return $this;
    }

    /**
     * Get DaysoffsAfternoon
     *
     * @return boolean 
     */
    public function getDaysoffsAfternoon()
    {
        return $this->DaysoffsAfternoon;
    }

    /**
     * Set daysoffsuserid
     *
     * @param \FullSix\ProjectForecastBundle\Entity\Users $daysoffsuserid
     * @return Daysoffs
     */
    public function setDaysoffsuserid(\FullSix\ProjectForecastBundle\Entity\Users $daysoffsuserid)
    {
        $this->daysoffsuserid = $daysoffsuserid;
    
        return $this;
    }

    /**
     * Get daysoffsuserid
     *
     * @return \FullSix\ProjectForecastBundle\Entity\Users 
     */
    public function getDaysoffsuserid()
    {
        return $this->daysoffsuserid;
    }

    /**
     * Get User
     *
     * @return \FullSix\ProjectForecastBundle\Entity\Users
     */
    public function getUser()
    {
        return $this->daysoffsuserid;
    }
}

server/src/FullSix/ProjectForecastBundle/Form/TasksType.php
<?php

namespace FullSix\ProjectForecastBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TasksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('projectsidprojects', null, array('label' => "Project"))
            ->add('tasksname', null, array('label' => "Task name"))
            ->add('tasksbeginat', 'date', array(
                    'label' => "Start date",
                    'widget' => 'single_text',
                    'format' => 'dd-MM-yyyy',
                    'attr'=> array('class'=>'has_datepicker')
                ))
            ->add('tasksendat', 'date', array(
                    'label' => "End date",
                    'widget' => 'single_text',
                    'format' => 'dd-MM-yyyy',
                    'attr'=> array('class'=>'has_datepicker')
                ))
            //->add('tasksorder', null, array('label' => "Ordre"))
            //->add('statesidstates', null, array('label' => "Etat"))
            //->add('lotsidlots', null, array('label' => "Lot"))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FullSix\ProjectForecastBundle\Entity\Tasks'
        ));
    }

    public function getName()
    {
        return 'fullsix_projectforecastbundle_taskstype';
    }
}

server/src/FullSix/ProjectForecastBundle/Controller/TasksController.php
<?php

namespace FullSix\ProjectForecastBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use FullSix\ProjectForecastBundle\Entity\Tasks;
use FullSix\ProjectForecastBundle\Form\TasksType;
use FullSix\ProjectForecastBundle\Form\TasksFromProjectType;
use APY\DataGridBundle\Grid\Source\Entity;
use APY\DataGridBundle\Grid\Action\RowAction;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Tasks controller.
 *
 * @Route("/tasks")
 */
class TasksController extends Controller {

    /**
     * Lists all Tasks entities.
     *
     * @Route("/", name="tasks")
     * @Template()
     */
    public function indexAction() {
        $source = new Entity('FullSixProjectForecastBundle:Tasks');
        $grid = $this->get('grid');
        $grid->setSource($source);

        $grid->setActionsColumnSeparator("&nbsp;&nbsp;");
        $rowAction_show = new RowAction("book", "tasks_show", false, "_self", array("title" => "Show"));
        $rowAction_show->setRouteParameters(array('id'));
        $grid->addRowAction($rowAction_show);

        $rowAction_edit = new RowAction("edit", "tasks_edit", false, "_self", array("title" => "Edit"));
        $rowAction_edit->setRouteParameters(array('id'));
        $grid->addRowAction($rowAction_edit);

        return $grid->getGridResponse('FullSixProjectForecastBundle::grid.html.twig',
            array(
                'title' => 'Tasks',
                'entity_new' => "tasks_new"
                )
            );
    }

    /**
     * Finds and displays a Tasks entity.
     *
     * @Route("/{id}/show", name="tasks_show")
     * @Template()
     */
    public function showAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('FullSixProjectForecastBundle:Tasks')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tasks entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to create a new Tasks entity.
     *
     * @Route("/new", name="tasks_new")
     * @Template()
     */
    public function newAction() {
        $entity = new Tasks();
        $form = $this->createForm(new TasksType(), $entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Displays a form to create a new Tasks entity.
     *
     * @Route("/newfromproject", name="tasksfromproject_new")
     * @Template()
     */
    public function newfromprojectAction($id) {
        $entity = new Tasks();

        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository('FullSixProjectForecastBundle:Projects')->find($id);

        $entity->setProjectsidprojects($project);
        $form = $this->createForm(new TasksFromProjectType(), $entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Displays a form to create a new Tasks entity.
     *
     * @Route("/newfromprojectresponsive", name="tasksfromproject_new_responsive")
     * @Template()
     */
    public function newfromprojectresponsiveAction($project_id) {
        $entity = new Tasks();

        $em = $this->getDoctrine()->getManager();
        $project = $em->getRepository('FullSixProjectForecastBundle:Projects')->find($project_id);

        $entity->setProjectsidprojects($project);
        $form = $this->createForm(new TasksFromProjectType(), $entity);

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Creates a new Tasks entity.
     *
     * @Route("/create/project/task/{projectId}", name="tasks_create_create_from_project")
     * @Method("POST")
     * @Template("FullSixProjectForecastBundle:Tasks:new.html.twig")
     */
    public function createFromProjectAction(Request $request, $projectId) {
        $entity = new Tasks();
        $entity->setTaskscreatedby($this->getUser());

        $form = $this->createForm(new TasksType(), $entity);

        //$this->tasksbeginat = \DateTime::createFromFormat('j-m-Y', $tasksbeginat);
        //tasksbeginat
        //tasksendat
        $form_values = $request->request->get('fullsix_projectforecastbundle_taskstype');

        $form->bind($form_values);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $project = $em->getRepository('FullSixProjectForecastBundle:Projects')->find($projectId);
            $ordre = $em->getRepository('FullSixProjectForecastBundle:Tasks')->findMaxOrdreByProjectId($projectId)+1;
            $entity->setTasksorder($ordre);
            $dates = $em->getRepository('FullSixProjectForecastBundle:Projects')->findDatesByProjetcTasks($projectId);
            if ($dates['maxDate'] == '') {
                $project->setProjectfirsttasktdate($entity->getTasksbeginat());
                $project->setProjectlasttasktdate($entity->getTasksendat());
            } else {
                if ($entity->getTasksbeginat() < $minDate = new \DateTime($dates['minDate'])) {
                    $entity->getProjectsidprojects()->setProjectfirsttasktdate($entity->getTasksbeginat());
                } else {
                    $project->setProjectfirsttasktdate($minDate);
                }
                if ($entity->getTasksendat() > $maxDate = new \DateTime($dates['maxDate'])) {
                    $project->setProjectlasttasktdate($entity->getTasksendat());
                } else {
                   $project->setProjectlasttasktdate($maxDate);
                }
            }
            $project->setProjectsupdated();

            $em->persist($entity);
            $em->flush();

            $response = new Response( json_encode( array('status' => 'success',
                'render' =>  $this->renderView("FullSixProjectForecastBundle:Tasks:_item.html.twig", array(
                    'task' => $entity,
                    'cycle' => 'cycle-not-defined'
                )))));
            $response->headers->set('Content-Type', 'application/json');
            return $response;
        }

        $response = new Response( json_encode( array('status' => 'error',
            'render' =>  $this->renderView("FullSixProjectForecastBundle:Tasks:newfromprojectresponsive.html.twig",
                        array(
                            'project_id' => $projectId,
                            'entity' => $entity,
                            'form' => $form->createView(),
                        )))));
            $response->headers->set('Content-Type', 'application/json');
            return $response;
    }

    /**
     * Creates a new Tasks entity.
     *
     * @Route("/create", name="tasks_create")
     * @Method("POST")
     * @Template("FullSixProjectForecastBundle:Tasks:new.html.twig")
     */
    public function createAction(Request $request) {
        $entity = new Tasks();
        $entity->setTaskscreatedby($this->getUser());

        $form = $this->createForm(new TasksType(), $entity);


        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $ordre = $em->getRepository('FullSixProjectForecastBundle:Tasks')->findMaxOrdreByProjectId($entity->getProjectsidprojects()->getId())+1;
            $entity->setTasksorder($ordre);
            $dates = $em->getRepository('FullSixProjectForecastBundle:Projects')->findDatesByProjetcTasks($entity->getProjectsidprojects()->getId());
            if ($dates['maxDate'] == '') {
                $entity->getProjectsidprojects()->setProjectfirsttasktdate($entity->getTasksbeginat());
                $entity->getProjectsidprojects()->setProjectlasttasktdate($entity->getTasksendat());
            } else {
                if ($entity->getTasksbeginat() < $minDate = new \DateTime($dates['minDate'])) {
                    $entity->getProjectsidprojects()->setProjectfirsttasktdate($entity->getTasksbeginat());
                } else {
                    $entity->getProjectsidprojects()->setProjectfirsttasktdate($minDate);
                }
                if ($entity->getTasksendat() > $maxDate = new \DateTime($dates['maxDate'])) {
                    $entity->getProjectsidprojects()->setProjectlasttasktdate($entity->getTasksendat());
                } else {
                    $entity->getProjectsidprojects()->setProjectlasttasktdate($maxDate);
                }
            }
            $entity->getProjectsidprojects()->setProjectsupdated();

            $em->persist($entity);
            $em->flush();

            return $this->redirect($request->headers->get('referer'));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Tasks entity.
     *
     * @Route("/{id}/edit", name="tasks_edit")
     * @Template()
     */
    public function editAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('FullSixProjectForecastBundle:Tasks')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Tasks entity.');
        }

        $editForm = $this->createForm(new TasksType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity' => $entity,
            'form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/_item.html.twig
<div data-action="{{ path('projects_edit_inplace') }}" class="row-fluid tasklist-line {{ cycle }}">

    <div class="span1" style="width:5px">
        {% if app.user is not null and is_granted('ROLE_PM') %}
            <form class="tasks-activation" method="POST" action="{{ path('tasks_activation', {'id': task.id}) }}">
                {% if task.isTrashed == false %}
                    <button type="submit" class="btn btn-small"><i id="tasks-activate" class="icon-pause" title="{{ 'common.action.trash'|trans }}"></i></button>
                {% else %}
                    <button type="submit" class="btn btn-small"><i id="tasks-activate" class="icon-play" title="{{ 'common.action.activate'|trans }}"></i></button>
                {% endif %}
            </form>
        {% endif %}
    </div>
    <div id="Tasks_tasksname_{{ task.id }}" class="span2 table-cell editable-field">
        <span>{{ task.tasksname }}</span>
    </div>
    <div id="Tasks_tasksbeginat_{{ task.id }}" class="span1 table-cell editable-field">
        <span>{{ task.tasksbeginat|date('d-m-Y') }}</span>
    </div>
    <div id="Tasks_tasksendat_{{ task.id }}" class="span1 table-cell editable-field">
        <span>{{ task.tasksendat|date('d-m-Y') }}</span>
    </div>
    <div class="span1 btn-add-taskload" >
        {% if app.user is not null and is_granted('ROLE_PM') %}
            {% if task.taskstasksloads is defined and task.taskstasksloads|length > 0 %}
                <button class="btn btn-primitive submit show-form" type="button">+</button>
            {% endif %}
        {% endif %}

    </div>
    <div class="span1" style="width:10px"> </div>
    <div class="span1 table-head">
        <span class="">Job</span>
    </div>
    <div class="span1 table-head">
        <span class="" >Volume</span>
    </div>
    <div class="span2 table-head">
        <span class="" >Assignment</span>
    </div>
    <div class="span2 table-head">
        <span class="" >Providers</span>
    </div>
</div>

<div class="row-fluid arrondi fcast-projectdetail-tasklist" id="tasklist_{{ task.id }}">

    {% block asksloadsListHeader %}{% endblock %}

    {% if app.user is not null and is_granted('ROLE_PM') %}
        <div class="row-fluid areaAdd fcast-fieldsaddfee {% if task.taskstasksloads is defined and task.taskstasksloads|length > 0 %}hidden-form{% endif %}">
            {% render(controller('FullSixProjectForecastBundle:Tasksloads:newfromproject_responsive', {'task_id': task.id })) %}
        </div>
    {% endif %}

    {% block tasksloadsList %}{% endblock %}
</div>

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/edit.html.twig
{% extends "FullSixProjectForecastBundle:Tasks:new.html.twig" %}

{% block title%}
    <title>Projects Forecast : Edition d'une tache</title>
{% endblock %}

{% block formTitle %}
    <h1>Edition de la tâche "{{ entity.tasksname }}"</h1>
{% endblock %}

{% block formParam %}
    action="{{ path('tasks_update', { 'id': entity.id }) }}"
{% endblock %}

{% block formAction %}
    {{ parent() }}
    <li>
        <form action="{{ path('tasks_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
{% endblock %}

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/new.html.twig
{% extends "FullSixProjectForecastBundle::form.html.twig" %}

{% block title%}
    <title>Projects Forecast : Création d'une tâche</title>
{% endblock %}

{% block formTitle %}
    <h1>Création d'une tâche</h1>
{% endblock %}

{% block formParam %}
    action="{{ path('tasks_create') }}"
{% endblock %}

{% block backLink %}
    href="{{ path('tasks') }}"
{% endblock %}

{% block formAction %}
    {% if entity.projectsidprojects %}
    <li>
        <a href="{{ path('projects_details', { 'id': entity.projectsidprojects.id }) }}">Return to project</a>
    </li>
    {% endif %}
{% endblock %}

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/newfromproject.html.twig
{% extends "FullSixProjectForecastBundle::formpartial.html.twig" %}

{% block formTitle %}
    Add task
{% endblock %}

{% block form %}
<tr>
    <form action="{{ path('tasks_create') }}" accept-charset="" method="post" {{ form_enctype(form) }} class="form-horizontal">
        <td>{{ form_label(form.tasksname) }} {{ form_widget(form.tasksname) }} {{ form_errors(form.tasksname) }}</td>
        <td>{{ form_label(form.tasksbeginat) }} {{ form_widget(form.tasksbeginat) }} {{ form_errors(form.tasksbeginat) }}</td>
        <td>{{ form_label(form.tasksendat) }} {{ form_widget(form.tasksendat) }} {{ form_errors(form.tasksendat) }}</td>
        <td style="padding-top: 25px"><button type="submit" class="btn btn-primary">Add</button></td>
    {{ form_widget(form) }}
    </form>
</tr>
{% endblock %}

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/newfromprojectresponsive.html.twig
{% block form %}
{% spaceless %}
<div class="row-fluid fcast-titleaddtask">
    <div class="span12">
<form data-load="{{ path('projects_block_details', {'project_id': entity.getProjectsidprojects.id }) }}" novalidate id="{{ form.vars.full_name }}" action="{{ path('tasks_create_create_from_project', { 'projectId': entity.getProjectsidprojects.id }) }}" method="post" class="taskstypeform">
	{### {{ form_errors(form) }} ###}
        <div class="span6 tasksname">
            {{ form_label(form.tasksname) }}
            {{ form_widget(form.tasksname) }}
            {{ form_errors(form.tasksname) }}
        </div>
        <div class="span2 tasksbeginat">
            {{ form_label(form.tasksbeginat) }}
            {{ form_widget(form.tasksbeginat, { 'attr': {'class': 'has_datepicker'} }) }}
            {{ form_errors(form.tasksbeginat) }}
        </div>
        <div class="span2 tasksendat">
            {{ form_label(form.tasksendat) }}
            {{ form_widget(form.tasksendat, { 'attr': {'class': 'has_datepicker'} }) }}
            {{ form_errors(form.tasksendat) }}
        </div>
        <div class="span2">
            <button class="btn btn-primary btn-info submit" type="submit">Add new task</button>
        </div>
        {{ form_rest(form) }}
    </form>
</div>
</div>
{% endspaceless %}
{% endblock %}

server/src/FullSix/ProjectForecastBundle/Resources/views/Tasks/show.html.twig
{% extends "FullSixProjectForecastBundle::show.html.twig" %}

{% block title%}
    <title>Projects Forecast : Tâche</title>
{% endblock %}

{% block elementTitle %}
    Tâche "{{ entity.tasksname }}"
{% endblock %}

{% block backLink %}
    {{ path('tasks') }}
{% endblock %}

{% block editLink %}
    {{ path('tasks_edit', { 'id': entity.id }) }}
{% endblock %}

{% block deleteLink %}
    {{ path('tasks_delete', { 'id': entity.id }) }}
{% endblock %}

{% block elementDetails %}
    <dt>Id</dt><dd>{{ entity.id }}</dd>
    <dt>Tasksname</dt><dd>{{ entity.tasksname }}</dd>
    <dt>Tasksbeginat</dt><dd>{{ entity.tasksbeginat|date('Y-m-d H:i:s') }}</dd>
    <dt>Tasksendat</dt><dd>{{ entity.tasksendat|date('Y-m-d H:i:s') }}</dd>
    <dt>Tasksorder</dt><dd>{{ entity.tasksorder }}</dd>
    <dt>Tasksistrashed</dt><dd>{{ entity.isTrashed }}</dd>
    <dt>Taskscreated</dt><dd>{{ entity.taskscreated|date('Y-m-d H:i:s') }}</dd>
    <dt>Tasksupdated</dt><dd>{{ entity.tasksupdated|date('Y-m-d H:i:s') }}</dd>
{% endblock %}